# Generated by Django 3.2.7 on 2021-09-16 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detect_disturbance', '0002_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='store_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Storage Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='detect_disturbance/'),
        ),
    ]
